name: 'Runhuman QA Test'
description: 'Run human-powered QA tests in your CI/CD pipeline. Get real human feedback on UI, UX, and user flows.'
author: 'Runhuman'

branding:
  icon: 'check-circle'
  color: 'yellow'

inputs:
  api-key:
    description: 'Runhuman API key (starts with qa_live_). Store as secret!'
    required: true
  url:
    description: 'URL to test (must be publicly accessible)'
    required: true
  description:
    description: 'Test instructions for human tester'
    required: true
  output-schema:
    description: 'Optional JSON schema defining expected output structure. If omitted, only success/explanation are extracted.'
    required: false
  api-url:
    description: 'Runhuman API base URL'
    required: false
    default: 'https://runhuman.com'
  target-duration-minutes:
    description: 'Target test duration in minutes (1-60, default: 5)'
    required: false
    default: '5'
  allow-duration-extension:
    description: 'Allow tester to request more time (true/false)'
    required: false
    default: 'false'
  max-extension-minutes:
    description: 'Maximum extension minutes allowed (number or false)'
    required: false
  additional-validation-instructions:
    description: 'Custom instructions for the AI when validating test results (e.g., "Ignore minor CSS issues")'
    required: false
  can-create-github-issues:
    description: 'Auto-create GitHub issues from tester findings (true/false)'
    required: false
    default: 'false'
  screen-size:
    description: 'Screen size for testing. Use preset (desktop, laptop, tablet, mobile) or custom JSON {"width": 1920, "height": 1080}'
    required: false
    default: 'desktop'
  fail-on-error:
    description: 'Fail workflow if test fails (default: true)'
    required: false
    default: 'true'

outputs:
  status:
    description: 'Job status (completed, error, incomplete, abandoned)'
  success:
    description: 'Boolean - true if test succeeded, false otherwise'
  result:
    description: 'Full result object as JSON string'
  explanation:
    description: 'Tester explanation/findings'
  data:
    description: 'Extracted data as JSON string'
  cost-usd:
    description: 'Test cost in USD (e.g., 0.396)'
  duration-seconds:
    description: 'Test duration in seconds'
  job-id:
    description: 'Job ID for reference'
  tester-alias:
    description: 'Anonymous tester name (e.g., Phoenix)'
  tester-avatar-url:
    description: 'Tester avatar URL'
  tester-color:
    description: 'Tester color for UI theming'
  tester-data:
    description: 'Playwright session data as JSON (screenshots, video, console logs, network requests)'
  tester-response:
    description: 'Raw tester response text'

runs:
  using: 'node20'
  main: 'dist/index.js'
